### ISSUE TITLE
Error in slopeint function: intercept is wrong

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/AdultCoverage#3]
When I looked at the slopeint function the formula for the intercept is wrong:

 (1) intercept   <- with(codi,mean(leftterm[age %in% agesfit]) * (1/slope) - mean(rightterm[age %in% agesfit]))

I think it should be:

 (2) intercept   <- with(codi,mean(leftterm[age %in% agesfit])  - mean(rightterm[age %in% agesfit])) * slope

**Comment by timriffe** [comment]
This is now fixed on the `ggbsegmod` branch, and will be merged to the `master` branch soon.
