### ISSUE TITLE
Confusion about coverage returned by ggb

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/AdultCoverage#4]
The item called "coverage" returned by **ggb** is the coverage relative to census 2 or 1/b.  The TDE workbook (http://demographicestimation.iussp.org/content/generalized-growth-balance-method) gives the completeness relative to the average (geometric) coverage of the two censuses.  This is the completeness of the intercensal death **rates**.

The completeness listed in the graph title of **ggbChooseAge** does not match either of these values.  I haven't looked at the code for that.

**Comment by timriffe** [comment]
`ggb()` should be checked now. It's now ahead of `ggbChooseAges()`. I'll try to make that function run on modules so they don't get out of sync any more.
